services:
  flow2api:
    build: .
    container_name: flow2api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config/setting.toml:/app/config/setting.toml
      - ./browser_sessions:/app/browser_sessions
      - ./browser_data:/app/browser_data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:10.0
    restart: unless-stopped
